In [2]:
#The frompyfunc() method
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [3]:
#add() function:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [4]:
#trunc()
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [5]:
#fix():
import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [6]:
# The around() methode:
import numpy as np

arr = np.around(3.1666, 2)

print(arr)


3.17


In [7]:
# The floor() function :
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [8]:
# The ceil() function :
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [9]:
# the log2() function:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [10]:
# the log10() function :
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [11]:
# the log() function :
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [12]:
# function math.log() :
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [13]:
# Addition methode:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [14]:
# Summation methode:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)


12


In [15]:
# the prod() function:
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [16]:
# the cumprod() function:
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)


[   5   30  210 1680]


In [17]:
# The Lowest Common Multiple:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [18]:
# Greatest Common Denominator methode:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [19]:
# The reduce() method :
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)


4


In [20]:
# sinh()method :
import numpy as np

x = np.sinh(np.pi/2)

print(x)


2.3012989023072947


In [21]:
# cosh() method:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]
